server.port: 8888

spring:
  application.name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thomasdriscoll/config_server_values_public.git
          clone-on-start: true
#  security:
#    user: